# backend/app/core/constants.py
class Role:
    NATIONAL_ADMIN = "national_admin"
    FDA_ADMIN = "fda_admin"
    LEA_ADMIN = "lea_admin"
    FDA_PERSONNEL = "fda_personnel"
    LEA_PERSONNEL = "lea_personnel"

    ADMIN_ROLES = {FDA_ADMIN, LEA_ADMIN}
    PERSONNEL_ROLES = {FDA_PERSONNEL, LEA_PERSONNEL}
    AGENCY_ROLES = {
        "FDA": {FDA_ADMIN, FDA_PERSONNEL},
        "LEA-CIDG": {LEA_ADMIN, LEA_PERSONNEL},
    }


class UserStatus:
    INVITED = "invited"
    PENDING_APPROVAL = "pending_approval"
    ACTIVE = "active"

    #to be worked on later, optional
    REJECTED = "rejected"
    RETURNED = "returned"


# Which complaint statuses are allowed to move to which other
# statuses, per source. Prevents accidentally skipping steps (e.g.
# jumping straight from 'open' to 'completed') or moving a complaint
# somewhere it can never leave (like 'dismissed' -> anything).
VALID_COMPLAINT_TRANSITIONS = {
    "extension": {
        "open": ["under_review", "dismissed"],
        "under_review": ["takedown_requested", "dismissed"],
        "takedown_requested": ["completed", "dismissed"],
        "completed": [],
        "dismissed": [],
    },
    "walk_in": {
        "open": ["under_review", "dismissed"],
        "under_review": ["takedown_requested", "dismissed", "open"], #added "open", so recalling a verification request can send the complaint back to Ready to Send
        "takedown_requested": ["takedown_initiated", "dismissed"],
        "takedown_initiated": ["completed", "dismissed"],
        "completed": [],
        "dismissed": [],
    },
}

class AuditAction:
    # Shared actions (used across FDA, LEA-CIDG, and SuperAdmin)
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    LOGIN_FAILED = "LOGIN_FAILED"
    UPDATE_COMPLAINT_STATUS = "UPDATE_COMPLAINT_STATUS" #FDA/LEA-CIDG actions

    # FDA actions
    UPDATE_VERIFICATION_STATUS = "UPDATE_VERIFICATION_STATUS"
    CREATE_REGISTERED_PRODUCT = "CREATE_REGISTERED_PRODUCT"
    CONVERT_TO_REGISTERED_PRODUCT = "CONVERT_TO_REGISTERED_PRODUCT"
    UPDATE_REGISTERED_PRODUCT = "UPDATE_REGISTERED_PRODUCT"
    DELETE_REGISTERED_PRODUCT = "DELETE_REGISTERED_PRODUCT"
    CREATE_UNREGISTERED_ADVISORY = "CREATE_UNREGISTERED_ADVISORY"
    CONVERT_TO_UNREGISTERED_ADVISORY = "CONVERT_TO_UNREGISTERED_ADVISORY"
    UPDATE_UNREGISTERED_ADVISORY = "UPDATE_UNREGISTERED_ADVISORY"
    DELETE_UNREGISTERED_ADVISORY = "DELETE_UNREGISTERED_ADVISORY"
    UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE" 
    UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD" 
    UPDATE_SUPERADMIN_PASSWORD = "UPDATE_SUPERADMIN_PASSWORD" 

    # Personnel (FDA/LEA) account management — Superadmin acting on personnel
    INVITE_PERSONNEL = "INVITE_PERSONNEL"
    PERSONNEL_REQUEST_INVITE = "PERSONNEL_REQUEST_INVITE"
    INVITE_PERSONNEL_RESENT = "INVITE_PERSONNEL_RESENT"
    APPROVE_PERSONNEL_ACCOUNT = "APPROVE_PERSONNEL_ACCOUNT"
    SUSPEND_PERSONNEL_ACCOUNT = "SUSPEND_PERSONNEL_ACCOUNT"
    REACTIVATE_PERSONNEL_ACCOUNT = "REACTIVATE_PERSONNEL_ACCOUNT"
    DELETE_PERSONNEL_ACCOUNT = "DELETE_PERSONNEL_ACCOUNT"
    UNLOCK_PERSONNEL_ACCOUNT = "UNLOCK_PERSONNEL_ACCOUNT"
    EDIT_PERSONNEL_INFO = "EDIT_PERSONNEL_INFO"
    RESET_PERSONNEL_PASSWORD = "RESET_PERSONNEL_PASSWORD"
    PERSONNEL_REQUEST_PASSWORD_RESET = "PERSONNEL_REQUEST_PASSWORD_RESET"

    # Admin (FDA/LEA agency admin) account management — National Admin
    # (or eventually a peer agency admin, see handoff open decision #4)
    # acting on fda_admin/lea_admin accounts
    INVITE_ADMIN = "INVITE_ADMIN"
    INVITE_ADMIN_RESENT = "INVITE_ADMIN_RESENT"
    ADMIN_REQUEST_INVITE = "ADMIN_REQUEST_INVITE"
    APPROVE_ADMIN_ACCOUNT = "APPROVE_ADMIN_ACCOUNT"
    SUSPEND_ADMIN_ACCOUNT = "SUSPEND_ADMIN_ACCOUNT"
    REACTIVATE_ADMIN_ACCOUNT = "REACTIVATE_ADMIN_ACCOUNT"
    DELETE_ADMIN_ACCOUNT = "DELETE_ADMIN_ACCOUNT"
    UNLOCK_ADMIN_ACCOUNT = "UNLOCK_ADMIN_ACCOUNT"
    UPDATE_ADMIN_PASSWORD = "UPDATE_ADMIN_PASSWORD"

    # Superadmin account management — Superadmin acting on other superadmins
    INVITE_SUPERADMIN = "INVITE_SUPERADMIN" 
    INVITE_SUPERADMIN_RESENT = "INVITE_SUPERADMIN_RESENT" 
    SUPERADMIN_REQUEST_INVITE = "SUPERADMIN_REQUEST_INVITE" 
    APPROVE_SUPERADMIN_ACCOUNT = "APPROVE_SUPERADMIN_ACCOUNT"
    SUSPEND_SUPERADMIN_ACCOUNT = "SUSPEND_SUPERADMIN_ACCOUNT"
    REACTIVATE_SUPERADMIN_ACCOUNT = "REACTIVATE_SUPERADMIN_ACCOUNT"
    DELETE_SUPERADMIN_ACCOUNT = "DELETE_SUPERADMIN_ACCOUNT"
    UNLOCK_SUPERADMIN_ACCOUNT = "UNLOCK_SUPERADMIN_ACCOUNT"

    # LEA-CIDG actions
    CREATE_COMPLAINT_LOG = "CREATE_COMPLAINT_LOG"
    DELETE_COMPLAINT_LOG = "DELETE_COMPLAINT_LOG"
    UPDATE_COMPLAINT_LOG = "UPDATE_COMPLAINT_LOG"
    DELETE_VERIFICATION_REQUEST = "DELETE_VERIFICATION_REQUEST"
    CREATE_VERIFICATION_REQUEST = "CREATE_VERIFICATION_REQUEST"

    # System actions
    LOCK_PERSONNEL_ACCOUNT = "LOCK_PERSONNEL_ACCOUNT"
    LOCK_SUPERADMIN_ACCOUNT = "LOCK_SUPERADMIN_ACCOUNT"
    SUPERADMIN_PENDING_APPROVAL = "SUPERADMIN_PENDING_APPROVAL" 
    PERSONNEL_PENDING_APPROVAL = "PERSONNEL_PENDING_APPROVAL"

    LOCK_ADMIN_ACCOUNT = "LOCK_ADMIN_ACCOUNT"
    ADMIN_PENDING_APPROVAL = "ADMIN_PENDING_APPROVAL"